language: c
compiler:
  - gcc
script: ./testme.sh "makefile" "-DUSE_LTM -DLTM_DESC -DLTC_NO_ASM -I/usr/include" /usr/lib/libtommath.a
branches:
  only:
    - develop
before_script:
  - sudo apt-get install libtommath-dev
after_script:
  - cat gcc_2.txt
